spring:
  application:
    name: resource-search-backend

  # 数据库配置
  datasource:
    url: jdbc:mysql://116.205.244.106:3306/resource?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 202358hjq
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial

# PageHelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 9090
  servlet:
    context-path: /api

logging:
  level:
    org.example.mapper: DEBUG
    org.mybatis: DEBUG
    com.github.pagehelper: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# QQ频道爬虫配置
crawler:
  qq-channel:
    api-url: "https://pd.qq.com/qunng/guild/gotrpc/auth/trpc.qchannel.commreader.ComReader/GetGuildFeeds?bkn=949027396"
    cookie: "RK=cn0ZoLn/cb; ptcz=a0d378dbb20ead0b616760379518ca9bf966589da6e3d22dcf5162bd3c5a6525; uuid=144115351595185418; p_uin=o1985238626; _qpsvr_localtk=0.6726194106697341; pt4_token=OGal*bLdwijVh-lUUYmu796e0ZLTWwRHNocBcN8YeTg_; p_skey=ddkb0jpenbmOOJ80hQZ93cx0kUYGfTFD2GXTsqd8sU4_; uin=o1985238626; daid=823"
    guild-number: "pd97631607"
    get-type: 2
    sort-option: 1
    need-channel-list: false
    need-top-info: false
    max-pages: 1000
    page-delay-seconds: 5
    from-param: 7

# 夸克网盘配置
quark:
  pan:
    # 夸克网盘Cookie（需要配置有效的Cookie）
    cookie: "_UP_A4A_11_=wb9ca14dee084c08b2f79c525f29f803; __pus=342a34d04935582e0efc69977ea79704AATMz3ChOVKVS1H/wU2ZgPP7LTl8Q89mO1j4uVg3WL0ATvAntMj6ZYcs5kCT3O1xDZkaB18F40xQr/QhcEWaevQk; __kp=245aaee0-4bd7-11f0-88fc-1b9bbac101fb; __kps=AASU0G1po9aMTVoC4LJPkf2q; __ktd=QeYgGE9qIl95QH6lof60+A==; __uid=AASU0G1po9aMTVoC4LJPkf2q; b-user-id=776701fb-0cd3-9d60-db45-7b0d8982e234; __sdid=AASSmALXyDB+2vUet3zEPU8vjXdlvF12xfoVeM8BI9islmH/y2OtC2WFI82C2AKjZUU=; xlly_s=1; __puus=5239600f727e357eae6deb203dbaf288AATw26CY7kGhxFfUmmUqTcU0TmXYNRBwpfi0hIUcMqLyt830Nle5SqJAQnvjRcX+ZG4kF+oqOIqShgcXrrB8UBeOq5cGyCQxyKSZI8xHmFaxPUACeJnuOOAsXp6PuCgt3V627KbN+r5OtWr54uo3EBxF6OFoCWTy7QYTFa/EdCNSB8AXK8JYd9l+UEFohavz5kHtpC9upD+fYviGP0WB7rNy; isg=BN_f68KFy8quis_ZC6xN24ycbjNpRDPmiE_vhHEtIg7VAP6CeBdCNVSSxph-mAte; tfstk=g35sbXTlccm6gSdxld4EO9I2QzOf5yPy6qTArZhZkCdOkIsBYFkaIKrfdiIeXfR9BIipli8AgheDcwIXmhdVQh8AAZITSEzGG9cfrZfaSIzMsNADMurzai_GSIc1YLvA12FpywntXfee9XYd4brza77TBFAVJu5qmnJHXEdvWKp99yTwrIHxBiKppULrXIIADpnpoFnxDKLAJpKHkIKADIUB9HYXMnh8zXTbCH7_7GgPKWDVkNKIMjCTsdK70HYH86T6C3ppAjLNOF962NC7nVaBJ65BUpu4YBQlLGLBN5ik59QW6E10yxtXh1ABAgN-ieXOf6pfTrVR7CTXeIpIkjQBOHvC6QF-AeXd7tCGfqGvS15yh3vQkjv29_JReGg0rwd9kivlgucMXZQlZTR710Y1paOC4zGyVrKsh29oGetzRyMmnvitVNnZhiDpBeY64yaIUxv9-etzRyMmndLH84zQRYkc."
    # 默认保存目录ID（需要配置目标文件夹ID）
    default-save-directory-id: "24e30276ab7b45b6bea01e84ff2529da"
    # 请求间隔时间（毫秒）
    request-interval: 2000
    # 最大重试次数
    max-retry-count: 10
    # 任务超时时间（毫秒）
    task-timeout: 300000
    # 单次转存文件数量限制
    max-files-per-save: 40


