spring:
  application:
    name: resource-search-backend

  # 数据库配置
  datasource:
    url: jdbc:mysql://116.205.244.106:3306/resource?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 202358hjq
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial

# PageHelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.example.mapper: DEBUG
    org.mybatis: DEBUG
    com.github.pagehelper: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# QQ频道爬虫配置
crawler:
  qq-channel:
    api-url: "https://pd.qq.com/qunng/guild/gotrpc/auth/trpc.qchannel.commreader.ComReader/GetGuildFeeds?bkn=949027396"
    cookie: "RK=cn0ZoLn/cb; ptcz=a0d378dbb20ead0b616760379518ca9bf966589da6e3d22dcf5162bd3c5a6525; uuid=144115351595185418; p_uin=o1985238626; _qpsvr_localtk=0.6726194106697341; pt4_token=OGal*bLdwijVh-lUUYmu796e0ZLTWwRHNocBcN8YeTg_; p_skey=ddkb0jpenbmOOJ80hQZ93cx0kUYGfTFD2GXTsqd8sU4_; uin=o1985238626; daid=823"
    guild-number: "pd97631607"
    get-type: 2
    sort-option: 1
    need-channel-list: false
    need-top-info: false
    max-pages: 1000
    page-delay-seconds: 5
    from-param: 7


